In [67]:
# -*- coding: utf-8 -*-
import dataiku
import pandas as pd, numpy as np
from dataiku import pandasutils as pdu

In [68]:
# Read recipe inputs
blooming_days_joined = dataiku.Dataset("blooming_days_joined")
df = blooming_days_joined.get_dataframe()

In [69]:
df.tail()

     blooming_day                      date  year  month  day  temperature flower_status
8913          NaN  2021-02-03T00:00:00.000Z  2021      2    3         -6.2       not yet
8914          NaN  2021-02-04T00:00:00.000Z  2021      2    4         -5.5       not yet
8915          NaN  2021-02-05T00:00:00.000Z  2021      2    5         -2.8       not yet
8916          NaN  2021-02-06T00:00:00.000Z  2021      2    6          1.9       not yet
8917          NaN  2021-02-07T00:00:00.000Z  2021      2    7         -1.3       not yet

In [70]:
d = {}
for year in df.year.unique():
    blooming_day = df[df.year==year].blooming_day.unique()[0]
    d[year] = blooming_day

In [71]:
d

{2021: nan,
 1997: '1997-04-22T00:00:00.000Z',
 1998: '1998-04-14T00:00:00.000Z',
 1999: '1999-04-22T00:00:00.000Z',
 2000: '2000-04-26T00:00:00.000Z',
 2001: '2001-04-19T00:00:00.000Z',
 2002: '2002-04-14T00:00:00.000Z',
 2003: '2003-04-18T00:00:00.000Z',
 2004: '2004-04-16T00:00:00.000Z',
 2005: '2005-04-28T00:00:00.000Z',
 2006: '2006-04-30T00:00:00.000Z',
 2007: '2007-04-24T00:00:00.000Z',
 2008: '2008-04-16T00:00:00.000Z',
 2009: '2009-04-17T00:00:00.000Z',
 2010: '2010-04-27T00:00:00.000Z',
 2011: '2011-04-26T00:00:00.000Z',
 2012: '2012-04-27T00:00:00.000Z',
 2013: '2013-04-28T00:00:00.000Z',
 2014: '2014-04-23T00:00:00.000Z',
 2015: '2015-04-15T00:00:00.000Z',
 2016: '2016-04-16T00:00:00.000Z',
 2017: '2017-04-18T00:00:00.000Z',
 2018: '2018-04-20T00:00:00.000Z',
 2019: '2019-04-19T00:00:00.000Z',
 2020: '2020-04-20T00:00:00.000Z'}

In [73]:
df_bloom = df[df.flower_status=='bloom']
df_bloom

                  blooming_day                      date  year  month  day  temperature flower_status
112   1997-04-22T00:00:00.000Z  1997-04-22T00:00:00.000Z  1997      4   22         10.9         bloom
469   1998-04-14T00:00:00.000Z  1998-04-14T00:00:00.000Z  1998      4   14         13.2         bloom
842   1999-04-22T00:00:00.000Z  1999-04-22T00:00:00.000Z  1999      4   22         10.7         bloom
1212  2000-04-26T00:00:00.000Z  2000-04-26T00:00:00.000Z  2000      4   26         10.1         bloom
1570  2001-04-19T00:00:00.000Z  2001-04-19T00:00:00.000Z  2001      4   19         15.9         bloom
1930  2002-04-14T00:00:00.000Z  2002-04-14T00:00:00.000Z  2002      4   14         11.2         bloom
2299  2003-04-18T00:00:00.000Z  2003-04-18T00:00:00.000Z  2003      4   18         13.2         bloom
2663  2004-04-16T00:00:00.000Z  2004-04-16T00:00:00.000Z  2004      4   16         12.1         bloom
3040  2005-04-28T00:00:00.000Z  2005-04-28T00:00:00.000Z  2005      4   28         17.1         bloom
3407  2006-04-30T00:00:00.000Z  2006-04-30T00:00:00.000Z  2006      4   30         13.2         bloom
3766  2007-04-24T00:00:00.000Z  2007-04-24T00:00:00.000Z  2007      4   24         10.0         bloom
4124  2008-04-16T00:00:00.000Z  2008-04-16T00:00:00.000Z  2008      4   16         12.5         bloom
4490  2009-04-17T00:00:00.000Z  2009-04-17T00:00:00.000Z  2009      4   17          6.6         bloom
4865  2010-04-27T00:00:00.000Z  2010-04-27T00:00:00.000Z  2010      4   27         10.4         bloom
5229  2011-04-26T00:00:00.000Z  2011-04-26T00:00:00.000Z  2011      4   26         10.9         bloom
5596  2012-04-27T00:00:00.000Z  2012-04-27T00:00:00.000Z  2012      4   27         10.6         bloom
5962  2013-04-28T00:00:00.000Z  2013-04-28T00:00:00.000Z  2013      4   28          8.3         bloom
6322  2014-04-23T00:00:00.000Z  2014-04-23T00:00:00.000Z  2014      4   23          8.8         bloom
6679  2015-04-15T00:00:00.000Z  2015-04-15T00:00:00.000Z  2015      4   15         10.4         bloom
7046  2016-04-16T00:00:00.000Z  2016-04-16T00:00:00.000Z  2016      4   16          9.4         bloom
7413  2017-04-18T00:00:00.000Z  2017-04-18T00:00:00.000Z  2017      4   18         11.1         bloom
7780  2018-04-20T00:00:00.000Z  2018-04-20T00:00:00.000Z  2018      4   20         13.7         bloom
8144  2019-04-19T00:00:00.000Z  2019-04-19T00:00:00.000Z  2019      4   19          9.0         bloom
8624  2020-04-20T00:00:00.000Z  2020-04-20T00:00:00.000Z  2020      4   20         11.1         bloom

In [86]:
df_new = pd.DataFrame()
for year in np.sort(df.year.unique()):
    print(year)
    df_sub = df[df.year==year]
    df_sub['blooming_day_shift'] = df_sub["blooming_day"]
    
    if year < 2021:
        blooming_ind = df_bloom[df_bloom.year==year].index[0]
        df_sub.loc[df_sub.index > blooming_ind, "blooming_day_shift"] = d[year+1]
    else:
        None
    df_new = pd.concat([df_new, df_sub])

1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021

/Users/mmiyazaki/dataiku/Design/DATA_DIR/code-envs/python/python36/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/mmiyazaki/dataiku/Design/DATA_DIR/code-envs/python/python36/lib/python3.6/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [0]:
# Write recipe outputs
blooming_days_fixed = dataiku.Dataset("blooming_days_shifted")
blooming_days_fixed.write_with_schema(df_new)